In [39]:
import pandas as pd
import graphviz
from sklearn.tree import export_graphviz
from IPython.display import Image

In [2]:
Data = pd.read_csv('C:\\Users\\NISHANT\\3D Objects\\CSV_Files\\Decision_tree.csv')

In [3]:
pd.options.display.max_rows = 1500

In [4]:
Data

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  drugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  drugY
5     22   F  NORMAL        HIGH    8.607  drugX
6     49   F  NORMAL        HIGH   16.275  drugY
7     41   M     LOW        HIGH   11.037  drugC
8     60   M  NORMAL        HIGH   15.171  drugY
9     43   M     LOW      NORMAL   19.368  drugY
10    47   F     LOW        HIGH   11.767  drugC
11    34   F    HIGH      NORMAL   19.199  drugY
12    43   M     LOW        HIGH   15.376  drugY
13    74   F     LOW        HIGH   20.942  drugY
14    50   F  NORMAL        HIGH   12.703  drugX
15    16   F    HIGH      NORMAL   15.516  drugY
16    69   M     LOW      NORMAL   11.455  drugX
17    43   M    HIGH        HIGH   13.972  drugA
18    23   M     LOW        HIGH    7.298  drugC
19    32   F    HIGH      NORMAL   25.974  drugY
20    57   M     LOW      NORMAL   19.128  drugY
21    63   M  NORMAL        HIGH   25.917  drugY
22    47   M     LOW      NORMAL   30.568  drugY
23    48   F     LOW        HIGH   15.036  drugY
24    33   F     LOW        HIGH   33.486  drugY
25    28   F    HIGH      NORMAL   18.809  drugY
26    31   M    HIGH        HIGH   30.366  drugY
27    49   F  NORMAL      NORMAL    9.381  drugX
28    39   F     LOW      NORMAL   22.697  drugY
29    45   M     LOW        HIGH   17.951  drugY
30    18   F  NORMAL      NORMAL    8.750  drugX
31    74   M    HIGH        HIGH    9.567  drugB
32    49   M     LOW      NORMAL   11.014  drugX
33    65   F    HIGH      NORMAL   31.876  drugY
34    53   M  NORMAL        HIGH   14.133  drugX
35    46   M  NORMAL      NORMAL    7.285  drugX
36    32   M    HIGH      NORMAL    9.445  drugA
37    39   M     LOW      NORMAL   13.938  drugX
38    39   F  NORMAL      NORMAL    9.709  drugX
39    15   M  NORMAL        HIGH    9.084  drugX
40    73   F  NORMAL        HIGH   19.221  drugY
41    58   F    HIGH      NORMAL   14.239  drugB
42    50   M  NORMAL      NORMAL   15.790  drugY
43    23   M  NORMAL        HIGH   12.260  drugX
44    50   F  NORMAL      NORMAL   12.295  drugX
45    66   F  NORMAL      NORMAL    8.107  drugX
46    37   F    HIGH        HIGH   13.091  drugA
47    68   M     LOW        HIGH   10.291  drugC
48    23   M  NORMAL        HIGH   31.686  drugY
49    28   F     LOW        HIGH   19.796  drugY
50    58   F    HIGH        HIGH   19.416  drugY
51    67   M  NORMAL      NORMAL   10.898  drugX
52    62   M     LOW      NORMAL   27.183  drugY
53    24   F    HIGH      NORMAL   18.457  drugY
54    68   F    HIGH      NORMAL   10.189  drugB
55    26   F     LOW        HIGH   14.160  drugC
56    65   M    HIGH      NORMAL   11.340  drugB
57    40   M    HIGH        HIGH   27.826  drugY
58    60   M  NORMAL      NORMAL   10.091  drugX
59    34   M    HIGH        HIGH   18.703  drugY
60    38   F     LOW      NORMAL   29.875  drugY
61    24   M    HIGH      NORMAL    9.475  drugA
62    67   M     LOW      NORMAL   20.693  drugY
63    45   M     LOW      NORMAL    8.370  drugX
64    60   F    HIGH        HIGH   13.303  drugB
65    68   F  NORMAL      NORMAL   27.050  drugY
66    29   M    HIGH        HIGH   12.856  drugA
67    17   M  NORMAL      NORMAL   10.832  drugX
68    54   M  NORMAL        HIGH   24.658  drugY
69    18   F    HIGH      NORMAL   24.276  drugY
70    70   M    HIGH        HIGH   13.967  drugB
71    28   F  NORMAL        HIGH   19.675  drugY
72    24   F  NORMAL        HIGH   10.605  drugX
73    41   F  NORMAL      NORMAL   22.905  drugY
74    31   M    HIGH      NORMAL   17.069  drugY
75    26   M     LOW      NORMAL   20.909  drugY
76    36   F    HIGH        HIGH   11.198  drugA
77    26   F    HIGH      NORMAL   19.161  drugY
78    19   F    HIGH        HIGH   13.313  drugA
79    32   F     LOW      NORMAL   10.840  drugX
80    60   M    HIGH        HIGH   1

In [5]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [6]:
Data.describe()

Age     Na_to_K
count  200.000000  200.000000
mean    44.315000   16.084485
std     16.544315    7.223956
min     15.000000    6.269000
25%     31.000000   10.445500
50%     45.000000   13.936500
75%     58.000000   19.380000
max     74.000000   38.247000

In [7]:
Data.corr()

C:\Users\NISHANT\AppData\Local\Temp\ipykernel_21092\3328628840.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  Data.corr()


Age   Na_to_K
Age      1.000000 -0.063119
Na_to_K -0.063119  1.000000

In [8]:
import category_encoders as ce

In [9]:
encoder = ce.OneHotEncoder()

In [10]:
Data_encoded = encoder.fit_transform(Data)

In [11]:
Data_encoded

Age  Sex_1  Sex_2  BP_1  BP_2  BP_3  Cholesterol_1  Cholesterol_2  \
0     23      1      0     1     0     0              1              0   
1     47      0      1     0     1     0              1              0   
2     47      0      1     0     1     0              1              0   
3     28      1      0     0     0     1              1              0   
4     61      1      0     0     1     0              1              0   
5     22      1      0     0     0     1              1              0   
6     49      1      0     0     0     1              1              0   
7     41      0      1     0     1     0              1              0   
8     60      0      1     0     0     1              1              0   
9     43      0      1     0     1     0              0              1   
10    47      1      0     0     1     0              1              0   
11    34      1      0     1     0     0              0              1   
12    43      0      1     0     1     0              1              0   
13    74      1      0     0     1     0              1              0   
14    50      1      0     0     0     1              1              0   
15    16      1      0     1     0     0              0              1   
16    69      0      1     0     1     0              0              1   
17    43      0      1     1     0     0              1              0   
18    23      0      1     0     1     0              1              0   
19    32      1      0     1     0     0              0              1   
20    57      0      1     0     1     0              0              1   
21    63      0      1     0     0     1              1              0   
22    47      0      1     0     1     0              0              1   
23    48      1      0     0     1     0              1              0   
24    33      1      0     0     1     0              1              0   
25    28      1      0     1     0     0              0              1   
26    31      0      1     1     0     0              1              0   
27    49      1      0     0     0     1              0              1   
28    39      1      0     0     1     0              0              1   
29    45      0      1     0     1     0              1              0   
30    18      1      0     0     0     1              0              1   
31    74      0      1     1     0     0              1              0   
32    49      0      1     0     1     0              0              1   
33    65      1      0     1     0     0              0              1   
34    53      0      1     0     0     1              1              0   
35    46      0      1     0     0     1              0              1   
36    32      0      1     1     0     0              0              1   
37    39      0      1     0     1     0              0              1   
38    39      1      0     0     0     1              0              1   
39    15      0      1     0     0     1              1              0   
40    73      1      0     0     0     1              1              0   
41    58      1      0     1     0     0              0              1   
42    50      0      1     0     0     1              0              1   
43    23      0      1     0     0     1              1              0   
44    50      1      0     0     0     1              0              1   
45    66      1      0     0     0     1              0              1   
46    37      1      0     1     0     0              1              0   
47    68      0      1     0     1     0              1              0   
48    23      0      1     0     0     1              1              0   
49    28      1      0     0     1     0              1              0   
50    58      1      0     1     0     0              1              0   
51    67      0      1     0     0     1              0              1   
52    62      0      1     0     1     0              0              1   
53    24 

In [12]:
Data_encoded.corr()

Age     Sex_1     Sex_2      BP_1      BP_2      BP_3  \
Age            1.000000 -0.102027  0.102027 -0.099782  0.112909 -0.009025   
Sex_1         -0.102027  1.000000 -1.000000  0.021390 -0.058356  0.036868   
Sex_2          0.102027 -1.000000  1.000000 -0.021390  0.058356 -0.036868   
BP_1          -0.099782  0.021390 -0.021390  1.000000 -0.542767 -0.511811   
BP_2           0.112909 -0.058356  0.058356 -0.542767  1.000000 -0.443749   
BP_3          -0.009025  0.036868 -0.036868 -0.511811 -0.443749  1.000000   
Cholesterol_1  0.068234 -0.008811  0.008811 -0.095708 -0.042036  0.145118   
Cholesterol_2 -0.068234  0.008811 -0.008811  0.095708  0.042036 -0.145118   
Na_to_K       -0.063119  0.125008 -0.125008  0.104985  0.043345 -0.156355   
Drug_1        -0.031434  0.066724 -0.066724  0.061182  0.018942 -0.084656   
Drug_2        -0.032432 -0.025085  0.025085 -0.233316  0.429863 -0.190751   
Drug_3        -0.010926  0.024346 -0.024346 -0.481186  0.017383  0.495642   
Drug_4        -0.184476 -0.063997  0.063997  0.455601 -0.247285 -0.233181   
Drug_5         0.324941 -0.061975  0.061975  0.372699 -0.202289 -0.190751   

               Cholesterol_1  Cholesterol_2   Na_to_K    Drug_1    Drug_2  \
Age                 0.068234      -0.068234 -0.063119 -0.031434 -0.032432   
Sex_1              -0.008811       0.008811  0.125008  0.066724 -0.025085   
Sex_2               0.008811      -0.008811 -0.125008 -0.066724  0.025085   
BP_1               -0.095708       0.095708  0.104985  0.061182 -0.233316   
BP_2               -0.042036       0.042036  0.043345  0.018942  0.429863   
BP_3                0.145118      -0.145118 -0.156355 -0.084656 -0.190751   
Cholesterol_1       1.000000      -1.000000 -0.010000  0.002712  0.286166   
Cholesterol_2      -1.000000       1.000000  0.010000 -0.002712 -0.286166   
Na_to_K            -0.010000       0.010000  1.000000  0.797612 -0.223059   
Drug_1              0.002712      -0.002712  0.797612  1.000000 -0.269438   
Drug_2              0.286166      -0.286166 -0.223059 -0.269438  1.000000   
Drug_3             -0.175996       0.175996 -0.458615 -0.555684 -0.179338   
Drug_4              0.004861      -0.004861 -0.258416 -0.329371 -0.106299   
Drug_5             -0.008851       0.008851 -0.186612 -0.269438 -0.086957   

                 Drug_3    Drug_4    Drug_5  
Age           -0.010926 -0.184476  0.324941  
Sex_1          0.024346 -0.063997 -0.061975  
Sex_2         -0.024346  0.063997  0.061975  
BP_1          -0.481186  0.455601  0.372699  
BP_2           0.017383 -0.247285 -0.202289  
BP_3           0.495642 -0.233181 -0.190751  
Cholesterol_1 -0.175996  0.004861 -0.008851  
Cholesterol_2  0.175996 -0.004861  0.008851  
Na_to_K       -0.458615 -0.258416 -0.186612  
Drug_1        -0.555684 -0.329371 -0.269438  
Drug_2        -0.179338 -0.106299 -0.086957  
Drug_3         1.000000 -0.219229 -0.179338  
Drug_4        -0.219229  1.000000 -0.106299  
Drug_5        -0.179338 -0.106299  1.000000

In [13]:
Data_encoded

Age  Sex_1  Sex_2  BP_1  BP_2  BP_3  Cholesterol_1  Cholesterol_2  \
0     23      1      0     1     0     0              1              0   
1     47      0      1     0     1     0              1              0   
2     47      0      1     0     1     0              1              0   
3     28      1      0     0     0     1              1              0   
4     61      1      0     0     1     0              1              0   
5     22      1      0     0     0     1              1              0   
6     49      1      0     0     0     1              1              0   
7     41      0      1     0     1     0              1              0   
8     60      0      1     0     0     1              1              0   
9     43      0      1     0     1     0              0              1   
10    47      1      0     0     1     0              1              0   
11    34      1      0     1     0     0              0              1   
12    43      0      1     0     1     0              1              0   
13    74      1      0     0     1     0              1              0   
14    50      1      0     0     0     1              1              0   
15    16      1      0     1     0     0              0              1   
16    69      0      1     0     1     0              0              1   
17    43      0      1     1     0     0              1              0   
18    23      0      1     0     1     0              1              0   
19    32      1      0     1     0     0              0              1   
20    57      0      1     0     1     0              0              1   
21    63      0      1     0     0     1              1              0   
22    47      0      1     0     1     0              0              1   
23    48      1      0     0     1     0              1              0   
24    33      1      0     0     1     0              1              0   
25    28      1      0     1     0     0              0              1   
26    31      0      1     1     0     0              1              0   
27    49      1      0     0     0     1              0              1   
28    39      1      0     0     1     0              0              1   
29    45      0      1     0     1     0              1              0   
30    18      1      0     0     0     1              0              1   
31    74      0      1     1     0     0              1              0   
32    49      0      1     0     1     0              0              1   
33    65      1      0     1     0     0              0              1   
34    53      0      1     0     0     1              1              0   
35    46      0      1     0     0     1              0              1   
36    32      0      1     1     0     0              0              1   
37    39      0      1     0     1     0              0              1   
38    39      1      0     0     0     1              0              1   
39    15      0      1     0     0     1              1              0   
40    73      1      0     0     0     1              1              0   
41    58      1      0     1     0     0              0              1   
42    50      0      1     0     0     1              0              1   
43    23      0      1     0     0     1              1              0   
44    50      1      0     0     0     1              0              1   
45    66      1      0     0     0     1              0              1   
46    37      1      0     1     0     0              1              0   
47    68      0      1     0     1     0              1              0   
48    23      0      1     0     0     1              1              0   
49    28      1      0     0     1     0              1              0   
50    58      1      0     1     0     0              1              0   
51    67      0      1     0     0     1              0              1   
52    62      0      1     0     1     0              0              1   
53    24 

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
SS = StandardScaler()

In [16]:
SS.fit_transform(Data_encoded)

array([[-1.29159102,  1.040833  , -1.040833  , ..., -0.60816364,
        -0.36047677, -0.29488391],
       [ 0.16269866, -0.96076892,  0.96076892, ..., -0.60816364,
        -0.36047677, -0.29488391],
       [ 0.16269866, -0.96076892,  0.96076892, ..., -0.60816364,
        -0.36047677, -0.29488391],
       ...,
       [ 0.46567567, -0.96076892,  0.96076892, ...,  1.64429429,
        -0.36047677, -0.29488391],
       [-1.29159102, -0.96076892,  0.96076892, ...,  1.64429429,
        -0.36047677, -0.29488391],
       [-0.26146916,  1.040833  , -1.040833  , ...,  1.64429429,
        -0.36047677, -0.29488391]])

In [17]:
x_columns = Data_encoded.iloc[:,[0,1,2,3,4,5,6,7,8]]
x = Data_encoded.iloc[:,[0,1,2,3,4,5,6,7,8]].values

In [18]:
y = Data_encoded.iloc[:,[9,10,11,12]].values

In [19]:
x

array([[23.   ,  1.   ,  0.   , ...,  1.   ,  0.   , 25.355],
       [47.   ,  0.   ,  1.   , ...,  1.   ,  0.   , 13.093],
       [47.   ,  0.   ,  1.   , ...,  1.   ,  0.   , 10.114],
       ...,
       [52.   ,  0.   ,  1.   , ...,  1.   ,  0.   ,  9.894],
       [23.   ,  0.   ,  1.   , ...,  0.   ,  1.   , 14.02 ],
       [40.   ,  1.   ,  0.   , ...,  0.   ,  1.   , 11.349]])

In [20]:
y

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1,

In [21]:
x = SS.fit_transform(x)

In [22]:
x

array([[-1.29159102,  1.040833  , -1.040833  , ...,  0.97043679,
        -0.97043679,  1.28652212],
       [ 0.16269866, -0.96076892,  0.96076892, ...,  0.97043679,
        -0.97043679, -0.4151454 ],
       [ 0.16269866, -0.96076892,  0.96076892, ...,  0.97043679,
        -0.97043679, -0.82855818],
       ...,
       [ 0.46567567, -0.96076892,  0.96076892, ...,  0.97043679,
        -0.97043679, -0.85908883],
       [-1.29159102, -0.96076892,  0.96076892, ..., -1.03046381,
         1.03046381, -0.28650033],
       [-0.26146916,  1.040833  , -1.040833  , ..., -1.03046381,
         1.03046381, -0.6571702 ]])

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 1)

In [25]:
x_train.shape

(160, 9)

In [26]:
x_test.shape

(40, 9)

In [27]:
from sklearn.ensemble import RandomForestClassifier

In [28]:
Classifier = RandomForestClassifier(n_estimators = 10,criterion = 'entropy')

In [29]:
Classifier.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10)

In [30]:
y_pred = Classifier.predict(x_test)

In [31]:
y_pred

array([[0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 1, 0],
       [1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 0, 0],
       [1, 0, 0, 0]], dtype=int64)

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
print(accuracy_score(y_pred,y_test)*100,'%')

97.5 %


In [34]:
from sklearn.tree import export_graphviz

In [35]:
from matplotlib import pyplot as plt
import numpy as np
Data_encoded.columns

Index(['Age', 'Sex_1', 'Sex_2', 'BP_1', 'BP_2', 'BP_3', 'Cholesterol_1',
       'Cholesterol_2', 'Na_to_K', 'Drug_1', 'Drug_2', 'Drug_3', 'Drug_4',
       'Drug_5'],
      dtype='object')

In [36]:
# check Important features
feature_importances_df = pd.DataFrame(
    {"feature": list(x_columns.columns), "importance": Classifier.feature_importances_}
).sort_values("importance", ascending=False)

# Display
feature_importances_df

feature  importance
8        Na_to_K    0.556151
0            Age    0.111853
3           BP_1    0.105183
4           BP_2    0.083198
5           BP_3    0.066616
6  Cholesterol_1    0.038224
7  Cholesterol_2    0.027701
2          Sex_2    0.008525
1          Sex_1    0.002550

In [42]:

for i in range(10):
    tree = Classifier.estimators_[i]
    dot_data = export_graphviz(tree,
                               feature_names=x_columns.columns,  
                               filled=True,  
                               max_depth=2, 
                               impurity=False, 
                               proportion=True)
    graph = graphviz.Source(dot_data)
    display(graph)

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH

ExecutableNotFound: failed to execute WindowsPath('dot'), make sure the Graphviz executables are on your systems' PATH